---
- name: Create group
  shell: groupadd -o -g {{ logstash_group_id }} {{ logstash_group }}
  ignore_errors: true
  tags:
    - skip_ansible_lint

- name: Create user
  user: name={{ logstash_user }} uid={{ logstash_user_id }} group={{ logstash_group }} non_unique=true

#Create required directories
- name: Create Directories
  file: path={{ item }} state=directory owner={{ logstash_user }} group={{ logstash_group }}
  with_items:
    - "{{conf_dir}}"
    - "{{conf_dir}}/pipeline"

- name: Copy jvm.options File for Instance
  template: src=jvm.options.j2 dest={{conf_dir}}/jvm.options owner={{ logstash_user }} group={{ logstash_group }} mode=0644 force=yes
  notify: restart logstash

- name: Copy logstash.yml File for Instance
  copy: src=logstash.yml dest={{conf_dir}}/logstash.yml owner={{ logstash_user }} group={{ logstash_group }} mode=0644 force=yes
  notify: restart logstash

- name: Copy pipelines
  template: src="{{ item }}" dest="{{conf_dir}}/pipeline/{{ item }}" owner={{ logstash_user }} group={{ logstash_group }} mode=0644 force=yes
  notify: restart logstash
  with_items:
    - input
    - output
    - filters


- name: Pull logstash image
  shell: docker pull "{{ logstash_docker_image }}:{{ logstash_version }}"
  register: result_docker
  changed_when: False
  until: result_docker|success
  retries: 3
  delay: 1
  tags:
    - update
    - skip_ansible_lint

- name: Start logstash containers
  docker_container:
    name: logstash
    image: "{{ logstash_docker_image }}:{{ logstash_version }}"
    network_mode: host
    state: present
    restart_policy: unless-stopped
    restart_retries: 3
    log_driver: json-file
    log_options:
      max-file: "1"
      max-size: "20m"
    labels: "{{ logstash_docker_labels }}"
    volumes:
      - /etc/logstash/jvm.options:/usr/share/logstash/config/jvm.options
      - /etc/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /etc/logstash/pipeline:/usr/share/logstash/pipeline
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime


- name: Create init-script rhel6
  copy: src=logstash_rhel6 dest=/etc/init.d/logstash owner=root group=root mode=0755
  when:
    ansible_distribution_major_version|int < 7
    and ansible_os_family == 'RedHat'

- name: Create init-script rhel7
  copy: src=logstash_rhel7 dest=/usr/lib/systemd/system/logstash.service owner=root group=root mode=0644
  when:
    ansible_distribution_major_version|int > 6
    and ansible_os_family == 'RedHat'

- name: Enable init-scripts
  service: name=logstash enabled=yes state=started
